#define	VOID	     	    1
#define	PRINT	     	    2
#define	READ	     	    3
#define	VAR	     	        4
#define	CONST	     	    5
#define	IF	     	        6
#define	ELSE	     	    7
#define	WHILE	     	    8
#define	ID                  9
#define	INT     	        10
#define STRING		        11
#define	LLAVEI     	        12
#define	LLAVED    	        13
#define	PARENI		        14
#define	PAREND              15
#define	PUNTCOM             16
#define	COMMA               17
#define	ASSIGNOP            18
#define	PLUSOP              19
#define	MINUSOP             20
#define	DIVOP	     	    21
#define	MULTOP	     	    22
